server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          url: https://github.com/yaziderman/cashew-config-server
          clone-on-start: true